[features]
seeds = false
skip-lint = false
[programs.localnet]
joketoearn = "FpoUMyXtiLdxVJ9XLAZWu7dDKEcDKsCZbExPFAV58unE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/yigo/.config/solana/devnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
